### ISSUE TITLE
C# extension methods for popular structures

### ISSUE THREAD

**Issue by wowbios** [hediet/vscode-debug-visualizer#106]
This plugin seems interesting to me. Do you need C# extension methods (for ex. VisualizeGrap(), VisualizeGrid() returning JSON) for popular structures like arrays, lists, queues, etc.? It is possible to make NuGet with extension methods to simply install this to user project and start using debug visualizer with C#.

**Comment by hediet** [comment]
I already implemented some C# infrastructure!

Are you interested in contributing? I'll add more details later.

**Comment by hediet** [comment]
https://github.com/hediet/rider-plugin-debug-visualizer-dotnet-sdk

**Comment by wowbios** [comment]
> 
> 
> I already implemented some C# infrastructure!
> 
> Are you interested in contributing? I'll add more details later.

Possibly, yes. It would be great if you will describe your plans for dotnet part. Or maybe I just cant find it?
