### ISSUE TITLE
truncated JSON strings in C++

### ISSUE THREAD

**Issue by mpseybold** [hediet/vscode-debug-visualizer#107]
Hi guys,
I fail to find how one can increase the string truncation threshold that is used for the expressions in the watch window.
Hence longer JSON strings that contain larger graphs cannot be used :(
This seems only to be an issue for C++ ?

Would it be possible to just specify a filename for the visualization, instead of an watch expression?

**Comment by hediet** [comment]
Hey, which debugger do you use? Does #53 help you?

> Would it be possible to just specify a filename for the visualization, instead of an watch expression?

How would that work?

**Comment by mpseybold** [comment]
Thank you for pointing out, issuing this command in the debugger console manually worked!
