### ISSUE TITLE
Graphviz engin support

### ISSUE THREAD

**Issue by fiveight58** [hediet/vscode-debug-visualizer#120]
Hi All:
Graphviz support many engin, like dot, circo, neato.
But I find this plugin only support dot engin. Am I right?
How can I use circo engin with this plugin? Thanks!

**Comment by hediet** [comment]
Viz-js seems to support other engines:
http://viz-js.com/

Here is where I use it:
https://github.com/hediet/visualization/blob/master/visualization-bundle/src/visualizers/graph/dot-graphviz-visualizer/GraphvizDotVisualizer.tsx#L14

Maybe some config options need to be exposed.

**Comment by fiveight58** [comment]
Thanks! I have resolved this by layout property in dot script.

digraph g1 {
    layout="circo";
    node [shape = doublecircle]; N4 N6;
    node [shape = circle];
    N0 -> N1 [ label = "{1,0}"];
    N1 -> N2 [ label = "{1,0}"];
    N2 -> N3 [ label = "{1,0}"];
    N3 -> N4 [ label = "{1,0}"];
    N4 -> N5 [ label = "{1,0}"];
    N5 -> N6 [ label = "{1,0}"];
    N6 -> N0 [ label = "{1,0}"];

    N0 -> N4 [ label = "{1,0}"];
    N1 -> N5 [ label = "{1,0}"];
    N2 -> N6 [ label = "{1,0}"];
    N3 -> N0 [ label = "{1,0}"];
    N4 -> N1 [ label = "{1,0}"];
    N5 -> N2 [ label = "{1,0}"];
    N6 -> N3 [ label = "{1,0}"];    
}

**Comment by hediet** [comment]
Thanks!
[Circo](https://hediet.github.io/visualization/?darkTheme=1&state=XQAAAAJnAgAAAAAAAABAqQlHM6T2Wc3r-_JdSPl8GMkG7VDMQ3ONzE9duOEBMIXgl7ts7cBIMRMu7cR9OUNId2weQzxb0AvvUvG3OMdJpY2zT5IgPnnCvk7UoYGZJcvcng959eNReRylWJqbACjTV8OZ5MEPexQP65FA7k2DkxuMKpTJ81urS9h4EV2Rkd9e3Y0pIvYVKKoS2Aznt1DhWheznxN_zSRHkPN6BEGlXbg__eLKuZJ6FSVrVDki5VFUdgI8gYhTwQMpQ128cddccQa7eHLJAcJYDL__3AuXAA)

[Dot](https://hediet.github.io/visualization/?darkTheme=1&state=XQAAAAJlAgAAAAAAAABAqQlHM6T2Wc3qjgpdSPl8GMkG7VDMQ3ONzE9duOEBMIXgl7ts7cBIMRMu7cR9OUNId2weQzxb0AvvUvG3OMdJpY2zT5IgPnnBsAsftptPpd-h1eTcpFHPJQs2yrB5nE8hVR0OUrKDPT613CCGlS43BQCXL-IJql0TQluRjQ3T-_Vqj2ZrmvNgVXWLPsdrbkoeWu5h7JbyTHS4q_Rj5-Qq9_IAbO-zQ7V-8hEetTo4ATBzuYzBfn5VQzoU_3B0xiBR4CaZXqKt-7l8N_63undefinedNc)
