### ISSUE TITLE
How to use this plugin in C code

### ISSUE THREAD

**Issue by hongshui3000** [hediet/vscode-debug-visualizer#131]
I don't seem to be using this plugin correctly
![1641877028(1)](https://user-images.githubusercontent.com/25566498/148883979-ef528218-cecd-40d8-b226-4c91cefc1b7a.png)

**Comment by hediet** [comment]
Hey, if you like, we can schedule a call and I can see how I can help you.

**Comment by hongshui3000** [comment]
Thanks Reply:
I have a few questions
In the readme:
```
All other languages and debuggers might work too. For languages with Basic Support, only JSON strings can be visualized - you must implement some logic that builds this JSON for your data structure! Fully supported languages offer Data Extractors which convert some well known data structures to json.
```
Should JSON be compiled into my C code?

Can you provide a C demo to help me understand this plugin?

I saw a C++ demo. After I compiled this demo and started debugging, I only need to put a variable(myGraphJson ) in the box and I still need to put gdb cmd: watch + variable(myGraphJson )

Thanks

**Comment by hediet** [comment]
Your string has to be a valid json document that matches the described json schema.

In that regard, there is no difference between C/C++/Rust/C#/...
Only JS and Python are a little bit special.

**Comment by hongshui3000** [comment]
Where should the json document be placed above? in my code? or somewhere else

**Comment by hediet** [comment]
> Is printing "myGraphJson" in the debug console a necessary step？？

No.
That demo should work. However, the compiler might remove that variable if it is not used.
