### ISSUE TITLE
Not seeing custom data extractor/visualizers in the visualizer options

### ISSUE THREAD

**Issue by jamesinvt** [hediet/vscode-debug-visualizer#134]
Hello!  First, this is a great extension.  Thanks for all your work!

However, I am a bit confused on how to make custom extractors and visualizers work.  I am testing with this [demo code](https://github.com/hediet/vscode-debug-visualizer/blob/master/demos/js/src/demo_custom-data-extractor.ts) and watching `f` with the visualizer, but I am not seeing the "My Extractor" in the extracter options.  I only see "To String" and "Object Graph".

I also don't seem to be able to figure out how to get the stuff in [custom-visualizer.js](https://github.com/hediet/vscode-debug-visualizer/blob/master/demos/js/custom-visualizer.js) to show up.  When I visualize `new Map([[1, 'Foo']]) as the docs state I see nothing in the extractor or visualizer options that match the screenshot in the docs.

A push in the right direction would be appreciated.

**Comment by hediet** [comment]
Hmm, seems to work for me:

![image](https://user-images.githubusercontent.com/2931520/152811423-474d83d1-ae41-4fb9-92a6-865b795d20f3.png)

For custom visualizations, you need to configure a setting, e.g.:
```json
"debugVisualizer.js.customScriptPaths": [
    "${workspaceFolder}/custom-visualizer.js",
]
```

**Comment by jamesinvt** [comment]
Hey, I started with a fresh clone of the repo but I'm still not seeing here.  Here's exactly what I do(MacOs).  Let me know if I am doing something wrong...

1. Clone repo
2. `cd` into the `demos/js` dir
3. Run `yarn` to install the packages
4. run `yarn add @hediet/debug-visualizer-data-extraction` to install the data extraction package
5. Run the `yarn dev` command which runs the `tsc --watch` script
6. Open the `src/demo_custom-data-extractor.ts` file
7.  From here, I select `Node.js` in the `Run and Debug` drop down.  There are my options:
    * `build` (tried this with no luck)
    * `build-ui`
    * `build-data-extraction` (tried this with no luck)
    * `build-extension`
    * `Javascript Debug Terminal`
    * `Run Current File`
8. (This may be where my mistake is) I select `Run Current File` my other options are all to build the project
9. I open a new visualizer window and watch `f`
10. I do not see the option for the custom data extractor.  

One thing that I am noticing is that there are two global variables `i` and `n` that both seem to hold the data for the extractors (see screenshots)

`i` is coming from `@hediet/data-extractor-api/v2` and DOES include the `my-extracter` data, along with 

`n` is coming from `@hediet/data-extractor-api/v3` and DOES NOT include the `my-extracter` data.  

Here are the screenshots:

I can see it here:
![v2](https://user-images.githubusercontent.com/2023458/152827878-6e456f3a-1a76-4330-b0f2-641de6c8e18a.png)

Not showing here:
![v3](https://user-images.githubusercontent.com/2023458/152826675-0ff0c2ad-2dad-47e6-8d98-0d77d0b1627b.png)

**Comment by jamesinvt** [comment]
Welp, as soon as I posted this follow up I was able to figure it out.

If anyone stumbles upon this from Google.  Here are the steps I took to fix:

1. I removed `@hediet/debug-visualizer-data-extraction` from the package.json and ran `yarn` again
2. Went to the root folder `vscode-debug-visualizer`
3. Ran `yarn` 
4. Ran `yarn build-data-extraction` and `yarn build-extension`
5. Went back into the `demos/js` dir and ran `yarn dev`
6. Selected `Run Current File` from the `Node.js` options in `Run and Debug` menu
7. I am not seeing the custom data extractor ant the `n` global that comes from `data-extractor-api/v3` is now showing the correct data

Thanks for your time!

**Comment by hediet** [comment]
Btw. I don't recommend to use the package @hediet/debug-visualizer-data-extraction except for types, rather use the new custom visualizer scripts.

They support nice hot-reloading and are only loosly coupled to your project.

**Comment by jamesinvt** [comment]
I might be a bit confused with how the stuff in `custom-visualizer.js` gets loaded in.  When I just use `Run Current File`  in the Run and Debug options after selecting `Node.js` as the environment(this is just a default launch option), none of the visualizers in that file shows up in the extractors options.  When I run `yarn dev` in `/extension` and `/webview` then run `Run Extension (Web UI)` it does show up. 

I've gone through the docs multiple times and it doesn't seem like this is the expected way to run this unless you are doing development on the extension itself -- am I wrong?  I feel like I'm missing something..

**Comment by hediet** [comment]
> When I run yarn dev in /extension and /webview then run Run Extension (Web UI) it does show up.

This is when you want to develop the extension itself.

> I might be a bit confused with how the stuff in custom-visualizer.js gets loaded in

It is just evaled into your debug session, thus it should work with browsers, electron and nodejs.

This works for me reliably:

![recording](https://user-images.githubusercontent.com/2931520/152975801-a52c4211-6632-43fa-b240-482e05f71222.gif)

**Comment by jamesinvt** [comment]
I was able to get this working.  Thanks for taking the time.
