### ISSUE TITLE
CPP does not wqork

### ISSUE THREAD

**Issue by Waddl3** [hediet/vscode-debug-visualizer#182]
Doesn't seem to let me use the visualizer debug, can I get some help? with cpp??

![image](https://user-images.githubusercontent.com/112538272/236405788-ecbf0dd6-3be8-45fb-9949-81ff6c860739.png)

**Comment by Klummel69** [comment]
Set a breakpoint on line 13. Only after the text has been assigned it can be displayed.

![2023-05-05_231503](https://user-images.githubusercontent.com/86959492/236570712-fe45a4ba-b636-4e22-a711-8ad549d1b472.png)
