### ISSUE TITLE
`yarn build` fails on most recent commit

### ISSUE THREAD

**Issue by williamli0707** [hediet/vscode-debug-visualizer#205]
The most recent commit relies on `RegisterVisualizerFn` and `libImplementation` from `@hediet/visualization-core` (`webview/src/model/Model.ts`); however, these were added in [this commit](https://github.com/hediet/visualization/commit/96115a9a701aa7801c908ca7d238146f48629e8b) in version 0.3.0 of visualization-core, which is not released to yarn. `yarn build` then fails after pulling version 0.2.0 of visualization-core.

**Comment by hediet** [comment]
Thanks, will fix this soon!

**Comment by hediet** [comment]
Fixed.
