### ISSUE TITLE
Unable to show geometries data

### ISSUE THREAD

**Issue by PARKCHEOLHEE-lab** [hediet/vscode-debug-visualizer#210]
This is my Python [Plotter](https://github.com/PARKCHEOLHEE-lab/debugvisualizer/blob/39ba7c3986d506c58159088200ddc06f22cdd8bc/debugvisualizer.py#L8) class for visualizing Shapely geometries. Could I get a way to fix the below? I think there are no problems when printing data for visualization but the vscode-debug-visualizer shows as below.

```
>>> print(Plotter(Polygon(random_coordinates)).visualize())
>>> {'kind': {'plotly': True}, 'data': [{...}]}
```

![image](https://github.com/hediet/vscode-debug-visualizer/assets/83874157/a13d2012-cdfb-4728-81b8-ee6bb0106f44)

**Comment by PARKCHEOLHEE-lab** [comment]
Hmm.. Previously, it was visualized well as just Python dictionary type but now it needs to convert the dictionary to JSON string.

![image](https://github.com/hediet/vscode-debug-visualizer/assets/83874157/053c9467-d71d-4e55-8b35-69e08f3e7565)

**Comment by hediet** [comment]
I think this happens when the data is not a simple value (like a string), but an object:

https://github.com/hediet/vscode-debug-visualizer/blob/master/extension/src/VisualizationBackend/GenericVisualizationSupport.ts#L69
