### ISSUE TITLE
Basic Swift Support

### ISSUE THREAD

**Issue by pakLebah** [hediet/vscode-debug-visualizer#23]
This extension doesn’t work with Swift on Mac Mojave. Please add support for Swift. Or do I need to do something to make it work with Swift? Thank you.

**Comment by hediet** [comment]
Can you try evaluating a string in the Debug Console and show me the result?

**Comment by pakLebah** [comment]
Here’s my code:
```swift
let s = "This is a string"
print(s)
```
I put a breakpoint on the first line. After the debugger passed the first line then I type `p s` on the Debug Console. Here’s the result:
```lldb
p s
(String) $R0 = "This is a string"
Module loaded: __lldb_dlopen_wrapper.
Module loaded: __lldb_caller_function.
Module loaded: /usr/lib/swift/libswiftSwiftOnoneSupport.dylib. Symbols loaded.
```
Is that you want?

**Comment by hediet** [comment]
Hmm, thats quite verbose. What do you see when watching that variable in the watch window?
Can you use a string with problemantic charactors? (`\n` or `"`)

**Comment by pakLebah** [comment]
> Hmm, thats quite verbose. What do you see when watching that variable in the watch window?

I saw `This is a string`, obviously.

> Can you use a string with problemantic characters? (\n or “)

Of course. I can debug any kind of string combination, including emoji, on VS Code using [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb).

The problem is, your extension failed to show the value, not the debugger.

**Comment by hediet** [comment]
> The problem is, your extension failed to show the value, not the debugger.

Thank you for clarifying that.

> I saw `This is a string`, obviously.

You might reconsider what you think is `obvious` and you should sharpen your understanding of details.
If `(String) $R0 = "This is a string"` was the result of the evaluation, my extension could never guess the actual start of the string content.
Now you say the result in the watch window is `This is a string` (which is a different result - clearly, the Swift debug adapter formats the output of an evaluation request differently in watch mode and debug console mode, what all the debug adapters I tested don't do).

Also, I still don't know how the string is escaped. Is the output exactly `This is a string`? or `"This is a string"`? What happens with line breaks or double quotes inside the string? Are they escaped or not?

My extension tries to parse the output of the debug adapter. Every debug adapter slightly differs in how the string is escaped.

**Comment by pakLebah** [comment]
In the debugger panel, it’s printed as `“This is a string”` (with the double quote) to indicate that it’s a string, I think. But on the Terminal, it’s printed as `This is a string` (without the double quote).

I don’t quite understand how the debugger formats the output. What is the debugger extension you’re using on your VS Code?

**Comment by hediet** [comment]
> What is the debugger extension you’re using on your VS Code?

I use `node` or `chrome` and they don't escape the string. If you use CodeLLDB, escaping should work, i.e. you can just visualize an expression that evaluates to a json string matching the schema of one of the visualizers.

**Comment by pakLebah** [comment]
> you can just visualize an expression that evaluates to a json string matching the schema of one of the visualizers.

And how to do that? Every time I put a string variable I wanted to evaluate into the visualizer, it shows this error:

```
Error: Could not parse `<value>` as JSON. Unexpected token s in JSON at position 0
```

What should I do?

**Comment by hediet** [comment]
Is `<value>` valid json? It must be.

**Comment by pakLebah** [comment]
It’s just the "`This is a string`" I mentioned above.

**Comment by hediet** [comment]
As I mentioned before, the string needs to be json. `This is a string` is not json.

**Comment by pakLebah** [comment]
As I asked before, how to do that? I’ve tried the `Text` interface and it failed too. I forgot the error message because I’m not in front of my laptop now. The point is, this extension wouldn’t work out of the box with unsupported languages.

**Comment by hediet** [comment]
You do that by serializing a json object and storing the result in a string. What do you mean with "I've tried the text interface"? I'll try to improve the error messages. But it does work out of the box with a lot of languages like Java of C# that also don't have built in support.
Try visualizing this expression:
```
"{\"kind\":{\"graph\":true},\"nodes\":[{\"id\":\"1\"},{\"id\":\"2\"}],\"edges\":[{\"from\":\"1\",\"to\":\"2\"}]}"
```

**Comment by hediet** [comment]
I verified that this extension works with swift, using the lldb debugger:
![image](https://user-images.githubusercontent.com/2931520/77253470-d3884100-6c5a-11ea-95ff-0371bd0a24cd.png)
You can find the [demo](https://github.com/hediet/vscode-debug-visualizer/tree/master/demos/swift) here.
