### ISSUE TITLE
Possible to get a vsix file

### ISSUE THREAD

**Issue by Redbeard101** [hediet/vscode-debug-visualizer#25]
Our terminals at work are intranet only, and we don't have access to the extension marketplace. Possible to get a vsix file for installation locally?

Cheers,

**Comment by hediet** [comment]
See [here](https://marketplace.visualstudio.com/items?itemName=hediet.debug-visualizer) and search for "Download Extension". That should get you the vsix.
I wonder how you can work without access to the internet...

**Comment by Redbeard101** [comment]
Oh thank you, we do have access, through virtual machines.
