### ISSUE TITLE
Basic C++ Support

### ISSUE THREAD

**Issue by sxtiann** [hediet/vscode-debug-visualizer#29]

**Comment by Disciple7** [comment]
This plugin is truly amazing! Please support C++ ! We C++ programmer/developer will be appreciate !

**Comment by jacmy23** [comment]
Waiting for the support of C++!!

**Comment by hediet** [comment]
Which debug adapters do you use for debugging C++?

**Comment by jacmy23** [comment]
> Which debug adapters do you use for debugging C++?

The gdb in MinGW.

**Comment by sxtiann** [comment]
> Which debug adapters do you use for debugging C++?

CLion IDE. The compiler is MinGW.

**Comment by hediet** [comment]
You can now find a cpp demo [here](https://github.com/hediet/vscode-debug-visualizer/tree/546d79ae6d2b051dd6ed6af1650020712d1f6e18/demos/cpp).
Closing this as the demo demonstrates basic support for C++.
