### ISSUE TITLE
Basic Golang Support

### ISSUE THREAD

**Issue by hantmac** [hediet/vscode-debug-visualizer#30]
Is this plugin support golang?

**Comment by hediet** [comment]
Can you try out to visualize this expression:
```
""{\"kind\":{\"graph\":true},\"nodes\":[{\"id\":\"1\"},{\"id\":\"2\"}],\"edges\":[{\"from\":\"1\",\"to\":\"2\"}]}""
```

If that does not work, can you enter the same expression in VS Codes watch window and post a screenshot of the result here?

**Comment by hantmac** [comment]
> Can you try out to visualize this expression:
> 
> ```
> ""{\"kind\":{\"graph\":true},\"nodes\":[{\"id\":\"1\"},{\"id\":\"2\"}],\"edges\":[{\"from\":\"1\",\"to\":\"2\"}]}""
> ```
> 
> If that does not work, can you enter the same expression in VS Codes watch window and post a screenshot of the result here?
1. Does not work
2. After entering the same expression in VS Codes watch window the screenshot is:
![image](https://user-images.githubusercontent.com/7600925/75418124-a1dacd80-596d-11ea-9bec-e1ed03b2179e.png)

**Comment by hediet** [comment]
You need to start a debug session by debugging a golang program!
This extension requires the debugger to evaluate expressions.
I'm working on improving the error messages.

**Comment by birdie7761** [comment]
![image](https://user-images.githubusercontent.com/22704751/75627574-42e6b400-5c0c-11ea-9e23-5eb2efd3b7a2.png)

**Comment by hediet** [comment]
@birdie7762 thanks for the screenshot ;) You can make it dynamic by calling a method that returns such a string.

**Comment by hediet** [comment]
@birdie7761 Would you mind porting [this demo](https://github.com/hediet/vscode-debug-visualizer/blob/master/demo/php/demo.php) to golang and creating a PR? That would be awesome! :)

**Comment by birdie7761** [comment]
![image](https://user-images.githubusercontent.com/22704751/75787108-30ea4a00-5da1-11ea-8e33-e9e3e5bf67ec.png)

**Comment by birdie7761** [comment]
```golang
package main

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"strconv"
	"time"
)

type Graph struct {
	Kind  map[string]bool `json:"kind"`
	Nodes []NodeGraphData `json:"nodes"`
	Edges []EdgeGraphData `json:"edges"`
}

type NodeGraphData struct {
	ID    string `json:"id"`
	Label string `json:"label,omitempty"`
	Color string `json:"color,omitempty"`
	Shape string `json:"shape,omitempty"`
}

type EdgeGraphData struct {
	From   string `json:"from"`
	To     string `json:"to"`
	Label  string `json:"label,omitempty"`
	ID     string `json:"id"`
	Color  string `json:"color,omitempty"`
	Dashes bool   `json:"dashes,omitempty"`
}

func NewGraph() *Graph {
	return &Graph{
		Kind:  map[string]bool{"graph": true},
		Nodes: []NodeGraphData{},
		Edges: []EdgeGraphData{},
	}
}

func (this *Graph) toString() string {
	rs, _ := json.Marshal(this)
	return string(rs)
}

func main() {
	rand.Seed(time.Now().UnixNano())
	graph := NewGraph()
	for i := 2; i < 100; i++ {
		id := strconv.Itoa(i)
		graph.Nodes = append(graph.Nodes, NodeGraphData{
			ID:    id,
			Label: id,
		})
		targetId := rand.Intn(i) + 1
		graph.Edges = append(graph.Edges, EdgeGraphData{
			From: id,
			To:   strconv.Itoa(targetId),
		})
		s := graph.toString()
		fmt.Printf("%s", s)
	}
}
```

**Comment by birdie7761** [comment]
`{"kind":{"graph":true},"nodes":[{"id":"2","label":"2"}],"edges":[{"from":"2","to":"2","id":""}]}`

**Comment by birdie7761** [comment]
> {"kind":{"graph":true},"nodes":[{"id":"2","label":"2"}],"edges":[{"from":"2","to":"2","id":""}]}

**Comment by hediet** [comment]
@birdie7761 thanks a lot :) If you want to be listed as contributer to this project in github, you can fork this repository and open a pull request with your file in the demo folder! (otherwise I can simply commit it by myself)

**Comment by hantmac** [comment]
That's Great!

**Comment by birdie7761** [comment]
> 
> 
> @birdie7761 thanks a lot :) If you want to be listed as contributer to this project in github, you can fork this repository and open a pull request with your file in the demo folder! (otherwise I can simply commit it by myself)

My English is very poor. I'm using a translator, so I haven't had a text reply to you before. PR I've created.(#37)

The golang serialized output of json cannot be displayed correctly. 
The error information is as follows:
`Error: Could not parse "{"kind":{"graph":true},"nodes":[{"id":"2","label":"2"}],"edges":...+32 more" as JSON. Unexpected token k in JSON at position 3`

**Comment by birdie7761** [comment]
The debug used is [delve](https://github.com/go-delve/delve)

**Comment by hediet** [comment]
Closing this as I've verified that the [golang demo](https://github.com/hediet/vscode-debug-visualizer/tree/fdab706e4e360f7b571584cbaea7688be707c46d/demos/golang) works.
