### ISSUE TITLE
Supporting non-JS debuggers

### ISSUE THREAD

**Issue by vadimcn** [hediet/vscode-debug-visualizer#32]
There's probably no general solution for turning data structures into JSON, however most debuggers support some kind of scripting, which could be used to bridge the gap.  If you made the expression that gets sent to the debugger configurable, developers would be able to provide the requisite glue code.  
Let's say you supported a config setting similar to this:
```javascript
"debugVisualizer.evalTemplates": {
    "<debugger-type>": { // DebugConfiguration::type
        "expression": "<some string with a placeholder>",
        "context": "<watch or repl>" 
    }
}
```

If someone wanted to use this extension with C++ in LLDB, they'd need to write a function, using LLDB's Python scripting, that can convert C++ objects to JSON , then tell Debug Visualizer how to use it:
```javascript
"debugVisualizer.evalTemplates": {
    "lldb": {
        "expression": "script to_json(\"${var}\")",
        "context": "repl"
    }
}
```

**Comment by hediet** [comment]
That's a pretty good idea! However, it might reduce the incentive to add proper support for all the specific debug adapters (which I think is fine).

I'm not a C++ guy and lldb/gdb are rather alien to me. I'm very curious in which ways these `evalTemplates` would be used and what could be achieved by them.

For what do you need the differentiation between `watch` or `repl` contexts though? The extension always uses the `watch` context, as the `repl` context sometimes is more verbose, making the result unparsable.

**Comment by vadimcn** [comment]
> it might reduce the incentive to add proper support for all the specific debug adapters (which I think is fine).

If templates are configurable, others will be able to create them and contribute back to your repo.   Otherwise, in order to add a new debugger, one would have to fork and build your extension, which raises the bar considerably.

> For what do you need the differentiation between watch or repl contexts though? 

In the case of lldb extension, debugger commands may be executed only in "repl" context.  Other debuggers may have this as well, so IMO, it'd be best to let developers choose the context.

**Comment by hediet** [comment]
There is now the configuration option `debugVisualizer.debugAdapterConfigurations` in 0.13.0:
```json
"debugVisualizer.debugAdapterConfigurations": {
	"type": "object",
	"additionalProperties": {
		"type": "object",
		"properties": {
			"expressionTemplate": {
				"type:": "string",
				"description": "A template for the final expression sent to the debugger for evaluation. Use `${expr}` to refer to the currently visualized expression."
			},
			"context": {
				"type": "string",
				"enum": [
					"watch",
					"repl"
				],
				"description": "The context to use for evaluating the expression."
			}
		}
	}
}
```

**Comment by hediet** [comment]
Closing as this should solve your use case.

**Comment by hediet** [comment]
Hey @vadimcn! Which context do you think should be used by default for evaluating expressions?
I used to chose `watch` as default, but many debug adapters truncate long strings, so I switched to `repl`. But for `repl`, the print command of lldb wraps the result in some other text. Also, having to use the print  command is confusing.
