### ISSUE TITLE
Can write a DEMO with the specificate language?

### ISSUE THREAD

**Issue by liaozhiwen** [hediet/vscode-debug-visualizer#36]

**Comment by hediet** [comment]
For which language?

**Comment by trueLoving** [comment]
I hope write a demo with javascript

**Comment by hediet** [comment]
You can find a JS demo [here](https://github.com/hediet/vscode-debug-visualizer/blob/master/demo/js/src/demo_singly-linked-list.js).

**Comment by hediet** [comment]
I'll reopen this issue once it becomes clearer what it is about.
