### ISSUE TITLE
Missing Libraries

### ISSUE THREAD

**Issue by HeIp** [hediet/vscode-debug-visualizer#40]
<img width="559" alt="image" src="https://user-images.githubusercontent.com/31706214/76126305-baca2b00-5fcc-11ea-9e84-9c3a16207015.png">
How do I get these libraries/install them to run the demo ?

**Comment by hediet** [comment]
Oh I think I accidentally put them on the git ignore list. Will push them soon!

**Comment by hediet** [comment]
[They are now included](https://github.com/hediet/vscode-debug-visualizer/tree/b007a6bdbdd7be56d06a1419aaaf83361a3ec3f5/demo/java/lib). It should work out of the box (if the java extension is installed).

**Comment by HeIp** [comment]
Awesome
