### ISSUE TITLE
Add a better tutorial.

### ISSUE THREAD

**Issue by bm-stschneider** [hediet/vscode-debug-visualizer#49]
I still don't know how to operate this thing. Is it usable with Promises? At what point can I use it and how? Do I need a breakpoint? Can it only output expressions or even a call stack? I'm very confused.

**Comment by hediet** [comment]
It's like the watch window that VS Code already provides in the debug pane. Except that it does not display the result as text, but interprets the result as data for specific visualizers.

> Is it usable with Promises?
As thus, you cannot visualize Promises directly, as there is no visualization for them.

> At what point can I use it and how?
You can use it whenever you can use VS Codes watch window.

> Can it only output expressions or even a call stack?
Now I am confused. It does not output expression, but visualizes the result of them, evaluated everytime the debugger pauses.

There is no visualizer for the current call stack yet, but VS Code already displays the call stack.

Did that clarify things?

**Comment by bm-stschneider** [comment]
For Promises and call stack yes. But how do I visualize something like .map or an iteration or even a simple object?

**Comment by bm-stschneider** [comment]
And how is the debug adapter chosen? When I run a node app it reports pwa-chrome instead of node?

**Comment by hediet** [comment]
How does it report `pwa-chrome`? This extension is not involved in chosing the debug adapter.
How would you like .map to be visualized? It's a function call. This extension visualizes data structures.
I'll try to record a video that will demonstrate how to use this extension for javascript.

**Comment by bm-stschneider** [comment]
It reports pwa-chrome in the output of the visualizer window.
Okay so I can't visualize iteration with map only with for loops? Is it a bit like in d3 enter update exit with a tick function?

**Comment by hediet** [comment]
Ah, now I understand the problem. Never really encountered the `pwa-chrome` debug adapter.
Why is VS Code using this debug adapter, and not the `node` debug adapter?
Which extensions provides the command `Debug: Create JavaScript Debug Terminal`?

**Comment by kwafok** [comment]
I have installed extension "vscode-js-debug", and it provide the command `Debug: Create JavaScript Debug Terminal`

https://github.com/microsoft/vscode-js-debug/blob/master/README.md#debug-nodejs-processes-in-the-terminal

**Comment by hediet** [comment]
I fixed it in 1.1.0. Should work with js-debug-nightly.

**Comment by hediet** [comment]
I'm closing this issue. Please reopen if the update does not fix it.
