### ISSUE TITLE
Couldn't add anything to the "Debug Visualizer" panel

### ISSUE THREAD

**Issue by akkaneror** [hediet/vscode-debug-visualizer#50]
As I read the usage from the page, it said that you can add variables to the panel just like "watch" does, but it will appear visually instead of just words. However, I couldn't get myself to add anything to to it as Im debugging.
![image](https://user-images.githubusercontent.com/42983232/79623494-7a80c100-80d1-11ea-9ca1-1112f55c289d.png)

**Comment by akkaneror** [comment]
> Interesting, that is clearly a bug. Can you tell me more about your setup? I see you are using a remote workspace? Can you focus the tab and run `developer: Open Webview Developer Tools`. Can you see an error there?

I'm not sure but I got ERR_CNNECTON_REFUSED. My Remote workspace still works as expected.
![image](https://user-images.githubusercontent.com/42983232/79704126-bbf5a580-8264-11ea-9203-e294cc232b29.png)

**Comment by hediet** [comment]
Should be fixed in 1.1.0. I just had to configure a portMapping.
