### ISSUE TITLE
Custom User Defined C/C++ Application Extractors

### ISSUE THREAD

**Issue by temportalflux** [hediet/vscode-debug-visualizer#52]
Hi hediet! This is a really lovely tool you've made!
I'm interested in looking into and perhaps eventually making a PR for allowing users to define their own C/C++ data extractors. As a test candidate, I intended to be working off of a Visual Studio solution for the running application.
After some preliminary research, I'm looking at running a C/C++ windows application alongside the test candidate which would allow the framework for the extractor to utilize the Windows headers to extract data from memory for the target application/test candidate. A brief, but useful, mock up of how the extractor can monitor memory of another application can be found at this [github repo](https://github.com/T-vK/Memory-Hacking-Class) I found. I hoping that this approach would allow the extractor to define a function or set of functions which reads the memory of their application and yields a json document which can then be sent via websocket to the webview and visualizer running in the browser.
I've set up a local environment/instance of this repository, but I'm curious if you have any guidance for providing data via websocket to the webview without using the vs-code extension.

**Comment by hediet** [comment]
Yeah, I would love to help you with that! I have no clue about C/C++ though.
If you like, we can schedule a virtual meeting! I think it's not so easy to write it up so that you find what you were looking for.

Do you intend to visualize data while stepping through the code or while the application is running?

**Comment by temportalflux** [comment]
I think both would be valuable, though I think the latter is the easier of the two to start with. If pursuing the memory observer approach via a parallel application, the visualizer would be reading whatever data the target application currently has in memory. That is fine for broad strokes debugging, but is more difficult to apply to stepping through a function.

I'd be down to chat via a virtual meeting, but I only have time in early morning EST or on weekends.

**Comment by hediet** [comment]
I thought about live visualizations too, but I don't have a clear vision of how the UI could look like.
I designed the visualization library (the thing that draws json objects) to be generic though.

[Early morning EST is fine](https://www.worldtimebuddy.com/?qm=1&lid=2950159,5&h=2950159&date=2020-5-13&sln=6.5-11)! [We can use jitsi meet](https://meet.jit.si/PronouncedFunctionsCorrectGreatly), if you don't mind.

**Comment by temportalflux** [comment]
I can meet up at 7am Easter/1pm CEST tomorrow (5/14) if you are available!

**Comment by hediet** [comment]
Perfect! See you soon on jitsi then!

**Comment by hediet** [comment]
Sorry, need another 5 minutes!

**Comment by hediet** [comment]
I'd love to hear about your progress! I'm closing this issue though, as it is not really something that needs to be changed in this extension.

**Comment by temportalflux** [comment]
Would it be possible to extract the `visualization` module into its own package such that it could be referenced by `npm install <git branch/repo>`?

**Comment by hediet** [comment]
That was my plan! It already is a package on its own, but just not published to npm yet.

You can use `yarn link` to use it in a different project right now.
