### ISSUE TITLE
view more than one object at the same time and automatically connect the lines 

### ISSUE THREAD

**Issue by sanriqing** [hediet/vscode-debug-visualizer#60]
I was wondering if it would be possible to view more than one object at the same time and automatically connect the lines if they are related, which might help to see the relationships between objects

**Comment by hediet** [comment]
> I was wondering if it would be possible to view more than one object at the same time

this is already possible

**Comment by hediet** [comment]
> I was wondering if it would be possible to view more than one object at the same time

It might not help in your usecase, but you can always open a second debug visualizer view.

Also, if you want to visualize the object graph of multiple objects, you can just visualize `{ obj1, obj2 }`.
