### ISSUE TITLE
request: properly document how to use the extension

### ISSUE THREAD

**Issue by Phrohdoh** [hediet/vscode-debug-visualizer#72]
This extension is passing the user's input (expr to visualize) _to the debugger as a command_ (in my case / Rust, this is `lldb`), which is almost never going to be valid nor will it output the properly-formatted JSON, so how is this extension supposed to be used?

The rust demo doesn't at all tell the user how to actually use the extension, just to set 2 breakpoints and look at the standard *watch* viewlet which obviously doesn't make use of this extension.

**Comment by hediet** [comment]
Hey there! Thanks for showing interest in this extension. For rust, there is no support for data extractors, so in order to visualize a data structure you must wrap it in an expression that returns a json formatted string.

This is done [here](https://github.com/hediet/vscode-debug-visualizer/blob/c420ff7f6f42a55ee3692016df3ffd7a5d29402b/demos/rust/src/main.rs#L85).
If you enter that string (`_s`) into the debug visualizer, you should see something.

**Comment by Phrohdoh** [comment]
The problem is that `_s` is passed to lldb as a command, which is invalid.
<img width="1012" alt="Screen Shot 2020-08-29 at 6 57 03 AM" src="https://user-images.githubusercontent.com/4861023/91636271-e438a200-e9c4-11ea-858a-2830bc70fbd9.png">

**Comment by hediet** [comment]
You're right, the rust demo is not well documented.

I'm not very familiar with lldb, but maybe `show _s` does the trick. What happens if you enter `_s` into the debug console?

Where do you see the hint to set the breakpoints and look at the standard watch viewlet btw.?

**Comment by hediet** [comment]
[Btw. it used to work](https://github.com/hediet/vscode-debug-visualizer/issues/31).

**Comment by Phrohdoh** [comment]
> Where do you see the hint to set the breakpoints and look at the standard watch viewlet btw.?

[breakpoint](https://github.com/hediet/vscode-debug-visualizer/blob/c420ff7f6f42a55ee3692016df3ffd7a5d29402b/demos/rust/src/main.rs#L84-L87), and [watch viewlet (to see what the ext will interpret)](https://github.com/hediet/vscode-debug-visualizer/blob/master/extension/README.md#supported-values).

**Comment by Phrohdoh** [comment]
regarding `show _s`, `lldb` outputs:
> error: 'show' is not a known command.

`print` is also not going to work since it prints with lldb-specific formatting (so not just the JSON expected).

**Comment by hediet** [comment]
> and look at the standard watch viewlet which obviously doesn't make use of this extension.

This is meant for debugging. What happens if you do that?

**Comment by hediet** [comment]
If that works, you might be able to configure a watch context for evaluating expressions in your vscode config:

```
"debugVisualizer.evalTemplates": {
    "lldb": {
        "expression": "${var}",
        "context": "watch"
    }
}
```

**Comment by Phrohdoh** [comment]
What happens if I do _what_, look at the watch viewlet?
It works as expected.

**Comment by Phrohdoh** [comment]
> If that works, you might be able to configure a watch context for evaluating expressions in your vscode config:
> 
> ```
> "debugVisualizer.evalTemplates": {
>     "lldb": {
>         "expression": "${var}",
>         "context": "watch"
>     }
> }
> ```

`debugVisualizer.evalTemplates` is an unknown config setting per vsc.

**Comment by hediet** [comment]
> What happens if I do what, look at the watch viewlet?

If you enter `_s` into vscode's watch viewlet. Does it show you the value as expected? If so, setting `"context": "watch"` as shown in the config in my comment should do the trick.

Sorry, I forgot that I changed the config name. It should be like this now:
```
"debugVisualizer.debugAdapterConfigurations": {
        "expressionTemplate": "${var}",
        "context": "watch"
}
```

**Comment by Phrohdoh** [comment]
With the following in my config
> ```
> "debugVisualizer.debugAdapterConfigurations": {
>     "lldb": {
>         "expressionTemplate": "${expr}",
>         "context": "watch"
>     }
> }
> ```

I get:
<img width="842" alt="Screen Shot 2020-08-29 at 7 12 15 AM" src="https://user-images.githubusercontent.com/4861023/91636528-fc112580-e9c6-11ea-9bc1-37c4d7e0c969.png">

**Comment by hediet** [comment]
Oh this is because in v2.0, the format of the grid visualizer changed slightly. The rust demo is really outdated, sorry for that.

If you provide json as done in the playground (https://hediet.github.io/visualization/), it should work.

**Comment by Phrohdoh** [comment]
Gotcha, I'll updated the code and see if I can get it working.
Thanks for the help, the extension looks insanely useful if I can just understand how to use it. :-)

**Comment by hediet** [comment]
Thanks ;) When you get it working, I would be very happy if you could open a PR for an updated rust demo, together with the vscode config (you can configure vscode settings per directory)!

**Comment by hediet** [comment]
Also, if you somehow manage to automatically turn [this schema](https://hediet.github.io/visualization/docs/visualization-data-schema.json) into rust structures, that would be really awesome!

**Comment by Phrohdoh** [comment]
https://github.com/Marwes/schemafy may be useful (or at least a good starting point / reference) for generating Rust structs from JSON schema.
