### ISSUE TITLE
Display outer variables

### ISSUE THREAD

**Issue by Esporia** [hediet/vscode-debug-visualizer#74]
Hello, thank you for this useful extension !

When break in a inner function (``helloer`` here), the extension doesn't display variables that are outside this inner function (``names`` here). How can I fix that, without redeclaring it inside my inner function.

Screenshots below (pictures are worth more than a thousand words) :

![image](https://user-images.githubusercontent.com/42718789/91637636-26380700-ea0a-11ea-8464-7973ee021b53.png)

![image](https://user-images.githubusercontent.com/42718789/91637655-4ec00100-ea0a-11ea-8fe0-9ccf9341b1e2.png)

**Comment by hediet** [comment]
Yeah, this is a problem... If you use "names" inside helloer somehow, nodejs does capture "names" and it should work.

You tried to select the parent stack frame. That would work in theory, but VS Code does not tell extensions which stackframe is currently selected :( I have to guess and always chose the most recent one.

**Comment by hediet** [comment]
You could add a logpoint with a side effect that writes "names" to "global.dbg_names"!

**Comment by Esporia** [comment]
How do you do that ?

global.dbg_names isn't recognized

![image](https://user-images.githubusercontent.com/42718789/91638105-5d5be780-ea0d-11ea-8b50-1d5d94958bb4.png)

**Comment by hediet** [comment]
You need to add a logpoint (e.g. a breakpoint with a log message) directly after `names` that prints this message: `{global.dbg_names = names}`.

**Comment by Esporia** [comment]
Ok thanks for this workaround

**Comment by Esporia** [comment]
Thanks for your quick answers by the way !
