### ISSUE TITLE
Not working with Java: “Could not parse evaluation result as JSON”

### ISSUE THREAD

**Issue by pcantrell** [hediet/vscode-debug-visualizer#77]
The extension doesn't seem to work at all with Java. For example:

- I open the Java demo from this project (`demos/java/src/app/App.java`)
- I set a breakpoint on line 10 and debug
- When it stops at the breakpoint, I choose Debug Visualizer: New View
- I enter `list` as the visualizer’s expression name
- I get this error (centered in the debug visualizer's view):

```
Could not parse evaluation result as JSON:

Unexpected token L in JSON at position 0

Evaluation result was:
LinkedList@9

Used debug adapter: java
```

I get similar error messages from other Java projects.

**Comment by robatipoor** [comment]
I get similar error messages from rust project

**Comment by hediet** [comment]
You need to visualize `list.visualize()`, not `list`. Java has no support for data extractors, so the thing you want to visualize must be a json string.

**Comment by pcantrell** [comment]
Ah, thank you! I'm afraid I failed to understand the docs on this.
