### ISSUE TITLE
Implement fully language-agnostic Evaluator

### ISSUE THREAD

**Issue by fwcd** [hediet/vscode-debug-visualizer#83]
### Motivation

VSCode uses the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/), which provides language-agnostic support for debugging, [evaluating expressions](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) and [inspecting the object graph](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Variables).

### Question

Would it be possible to implement e.g. an `Evaluator` purely in terms of VSCode's DAP client, so that this extension could support [any language with a debug adapter](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/)?

This would also fix issues like #63, #70, #79.

### Proposed Solution

I have seen that there is a [`GenericEvaluator`](https://github.com/hediet/vscode-debug-visualizer/blob/1dd0349483b2154951cd2e8cfb85e3efd2e6c4dd/extension/src/EvaluationWatchService/EvaluationEngine/GenericEvaluationEngine.ts), which currently relies on [parsing the evaluation response string](https://github.com/hediet/vscode-debug-visualizer/blob/1dd0349483b2154951cd2e8cfb85e3efd2e6c4dd/extension/src/EvaluationWatchService/EvaluationEngine/parseEvaluationResultFromGenericDebugAdapter.ts#L11). Many debug adapters provide more structured information about the result however, by including a `variablesReference` in the [`EvaluateResponse`](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate). Maybe it would be possible to use this to query the object's structure directly?

**Comment by hediet** [comment]
Thanks for your thoughts! 
However, I think I'm using the most language-agnostic way possible (which already includes leveraging the DAP).

I think data extractors cannot be implemented genericly, as they heavily rely on the semantics of the language and their data structures. I don't think the structured values of the DAP would help here. Can you further elaborate how you want to use the DAP information?

**Comment by fwcd** [comment]
I'm testing this with my Kotlin debug adapter:

![image](https://user-images.githubusercontent.com/30873659/91999429-a7f6a000-ed3c-11ea-993d-a1789776b0b4.png)

The debug adapter provides structural information about the objects referenced by each variable (e.g. `a` in this case), however not in direct a JSON format, but through DAP's variables API. My question is whether it would be possible for this extension to use the variables API to visualize the object graph directly from the variables API, instead of trying to parse the evaluation response string (which, in Kotlin's case, is just `"instance of ..."`) as JSON.

**Comment by fwcd** [comment]
@hediet I have prototyped my idea in the PR #84.
